# Generated by Django 4.2.20 on 2025-03-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_flight_arrival_expected_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='baggage_weight',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Hand', 'Hand'), ('Hold', 'Hold'), ('Hand and Hold', 'Hand and Hold')], default='none', max_length=15),
        ),
    ]
