# Generated by Django 4.2.20 on 2025-03-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_passenger_baggage_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='dietary_requirements',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
    ]
